apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svc.name }}
  namespace: {{ .Values.config.ns }}
spec:
  ports:
  - port: {{ .Values.svc.port }}
    protocol: TCP
    targetPort: {{ .Values.svc.targetPort }}
  selector:
    App: {{ .Values.config.labelSelector }}
  type: {{ .Values.svc.type }}
